id: I7FD3FD2C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T20:49:53+00:00'
last_modified: '2022-06-08T10:16:47.870267+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ294458
  title: མདོ་རྒྱུད་གཅེས་བཏུས་དགོས་པ་ཀུན་འབྱུང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '6014':
      image_group_id: I4CZ294589
      title: ''
      total_pages: 1362
      order: 1
      base_file: 6014.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
