id: P009334
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W4CZ294458
  title: མདོ་རྒྱུད་གཅེས་བཏུས་དགོས་པ་ཀུན་འབྱུང་།
  author: ''
  volumes:
    897e42a7645c4172bb43b3f4e3246e88:
      image_group_id: I4CZ294589
      title: ''
      volume_number: 1
      total_pages: 1362
      base_file: v001.txt
